apiVersion: apps/v1
kind: Deployment
metadata:
  name: Support
  namespace: MSM
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Support
  template:
    metadata:
      labels:
        app: Support
    spec:
      containers:
      - name: Support
        image: docker_en_progresion/miapp:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-configmap
        - secretRef:
            name: app-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20

