# -*- coding: utf-8 -*-
"""Firma Digital.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwg7iJGq_QgxEtZeC3ZjdqHQLGtzT65A

# **SCRIPT PARA FIRMAS DIGITALES**
"""

!pip install pycrypto

"""# Generación de claves



1.   Generación de claves publica y privada
2.   Guardado de Claves


"""

from Crypto.PublicKey import RSA
import time

# Generación de algoritmo RSA
time.clock = time.time
rsa = RSA.generate(1024)
# Generación de claves maestras
private_pem = rsa.exportKey()


with open('ClavePrivadaGXOElux.pem', 'wb') as f:
    f.write(private_pem)

public_pem = rsa.publickey().exportKey()
with open ('ClavePublicaGXOElux.pem', 'wb') as f:
    f.write(public_pem)

print("Se han generado las dos claves:")
print(("🔑 Privada: {}").format(private_pem))
print(("🔑 Publica: {}").format(public_pem))

"""# FIRMAR UN DOCUMENTO


1.   Creamos un hash cobre el contenido del documento
2.   Encriptamos el hash con nuestra clave privada
3.   El resultado es la firma digital




"""

from Crypto.Hash import SHA
from Crypto.Signature import PKCS1_v1_5 as Signature_pkcs1_v1_5
from Crypto.PublicKey import RSA
import base64

# Usar clave para firmar el archivo

def firma(message):
    with open ('ClavePrivadaGXOElux.pem') as f:
        key= f.read()
        rsakey = RSA.importKey(key)
        signer = Signature_pkcs1_v1_5.new(rsakey)

        #Cifrado HASH
        
        digest = SHA.new()
        
        #Firmamos
        
        digest.update(message)
        print("🔓 Contenido del documento: ", message)
        print("🔓 Calculamos hash del documento: ", digest.hexdigest())

        sign = signer.sign(digest)
        signature = base64.b64encode(sign)
            
    with open ('firma.pem', 'wb') as fp1:
        fp1.write(signature)
        fp1.close()
    print("🤟 Firma Creada", signature)
    print("🤟 Firma Guardada en : firma.pem")

    return signature

with open ("notas.txt", "r") as file:
    message=file.read()

message = message.encode()
signature = firma(message)

"""# FIRMAR EL DOCUMENTO



1.   Se comprueba la integridad del documento
2.   Se comprueba la identidad del firmante


"""

from Crypto.Hash import SHA
from Crypto.Signature import PKCS1_v1_5 as Signature_pkcs1_v1_5
from Crypto.PublicKey import RSA
import base64

def verificar(message, signature):
    with open('ClavePublicaGXOElux.pem') as f:
        key = f.read()
        rsakey = RSA.importKey(key)
        verifier = Signature_pkcs1_v1_5.new(rsakey)
        digest = SHA.new()
        
        # Asumimos que los datos estan codificados en base64
        digest.update(message)
        print("Hash del documento recibido: ", digest.hexdigest())
        print("Desencriptamos la firma para extraer el hash original")
        is_verify = verifier.verify(digest, base64.b64decode(signature))

    #devolvemos la respuesta

    if is_verify:
        print("✅ OK, los hashes coinciden. La firma del documento es valida")
        print("✅ El documento no ha sido alterado y su autor es quien dice ser")
    else:
        print("❌ La firma del documento no es correcta")
        print("❌ El documento o la firma han sido alterados o el firmante no es correcto")

with open("notas.txt", "r") as file:
    message = file.read()

with open("firma.pem", "r") as s:
    signature = s.read()

message=message.encode()
verificar(message, signature)