# Generated by Django 5.2.10 on 2026-01-29 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sql', models.TextField(help_text="Usa placeholders '?' para parámetros ODBC (posicionales).")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('ok', models.BooleanField(default=True)),
                ('params_json', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text="Orden posicional para '?'")),
                ('name', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('param_type', models.CharField(choices=[('int', 'Entero'), ('str', 'Texto'), ('date', 'Fecha'), ('bool', 'Booleano')], max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, max_length=200)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='core.query')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('query', 'name'), ('query', 'order')},
            },
        ),
    ]
