# Generated by Django 5.2.10 on 2026-02-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='query',
            name='sql',
            field=models.TextField(help_text="Usa placeholders '%s' (estilo Django). Ej: WHERE campo >= %s AND campo < %s"),
        ),
        migrations.AddField(
            model_name='query',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queries', to='core.querycategory'),
        ),
    ]
