# Generated by Django 5.2.10 on 2026-02-02 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_querycategory_alter_query_sql_query_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='querycategory',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos que pueden ver esta categoría. Si está vacío, la ve todo el mundo.', related_name='allowed_categories', to='auth.group'),
        ),
        migrations.CreateModel(
            name='UserCategoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_categories', models.ManyToManyField(blank=True, help_text='Categorías adicionales para este usuario (además de sus grupos).', related_name='extra_users', to='core.querycategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
