SELECT 
    'Taisa Logistics' AS 'NOMBRE_RECOGIDA','' AS 'NOMBRE_RECOGIDA_AMPLIADO', 'Avda. de la Veguilla, 20, Nave A' AS 'DIRECCION_RECOGIDA',
    '' AS 'DIRECCION_RECOGIDA_AMPLIADA', '1971' AS 'CODIGO_POSTAL_RECOGIDA', 'Cabanillas del Campo' AS 'CIUDAD_RECOGIDA',
    'ES' as 'PAIS_RECOGIDA', '608717032' AS 'TELEFONO_RECOGIDA', 'oscar.comendadormendoza@gxo.com' AS 'MAIL_REMITENTE',NombreDireccion AS 'NOMBRE_DESTINATARIO',
    '' AS 'NOMBRE_DESTINATARIO_AMPLIADO', Direccion1Direccion AS 'DIRECCION_DESTINATARIO', '' AS 'DIRECCION_DESTINATARIO_AMPLIADA',
    CodigoPostal AS 'CODIGO_POSTAL_DESTINATARIO', PoblacionDireccion AS 'CIUDAD_DESTINATARIO', 'ES' AS 'PAIS_DESTINATARIO',
    '' AS 'TELEFONO_DESTINATARIO', '' AS 'MAIL_DESTINATARIO', 'DAP' AS 'INCOTERMS',
    PoblacionDireccion AS 'LOCALIDAD_INCOTERMS', '1' AS 'UNIDADES', 'PALET' AS 'TIPO_BULTO',
    ROUND(PesoFiege,2) AS 'PESO_TOTAL', '' AS 'LARGO', '' AS 'ANCHO',
    '' AS 'ALTO', ROUND(volumenFiege,3) AS 'VOLUMEN_TOTAL', 'BEBIDAS' AS 'DESCRIPCION_MERCANCIA',
    '' AS 'REFERENCIA_PRODUCTO', 'NO' AS 'REMONTABLE',  RTRIM(PedidoDestinatarioDoc) + '/' + RTRIM(ObsDocumento1) AS 'OBSERVACIONES',
    RTRIM(AlbaranDoc) AS 'REFERENCIA_GENERAL', '43' AS 'PRODUCTO', FechaDoc AS 'FECHA_RECOGIDA_DESDE',
    FechaDoc AS 'FECHA_RECOGIDA_HASTA','SI' AS 'FIXDAY', FechaProgramadaDoc AS 'FECHA',
    '' AS 'PRENOTICE_CONTACT_NAME', '' AS 'PRENOTICE_MAIL', '' AS 'CONTACT_FDTBA_NAME',
    '' AS 'TELEFONO_FDTBA', '' AS 'FIXDAY_TO_BE_AGREED_AUTOMATED', '' AS 'ADUANAS',
    '' AS 'VALOR_MERCANCIA', '' AS 'VALOR_SEGURO', '' AS 'VALOR_CONTRAREMBOLSO',
    '' AS 'ADR', '' AS 'N_BULTOS', '' AS 'TIPO_BULTO',
    '' AS 'PESO', 'KILOS' AS 'UNIDAD_MEDIDA', 'NETO' AS 'BASE_PONDERAL',
    '' AS 'UN_ID', '' AS 'N_ETIQUETA', '' AS 'GRUPO_BULTOS',
    '' AS 'NOMBRE_ENVIO_ADECUADO', '' AS ' NOMBRE_TECNICO', '' AS 'DISPOSICION_ESPECIAL',
    '' AS 'CODIGO_TUNEL', '' AS 'NEM', '' AS 'TRANSPORT_CATEGORY', 
    '' AS 'RESIDUOS', '' AS 'CODIGO_EUROPEO_RESIDUOS', '' AS 'CANTIDAD_EXENTA',
    '' AS 'CANTIDAD_LIMITADA', '' AS 'PELIGROSIDAD_ENTORNO',
    '' AS 'EXTRA_1', '' AS 'EXTRA_2', '' AS 'EXTRA_3', '' AS 'EXTRA_4', '' AS 'EXTRA_5', '' AS 'EXTRA_6', 
    '' AS 'EXTRA_7', '' AS 'EXTRA_8', '' AS 'EXTRA_9', '' AS 'EXTRA_10', '' AS 'EXTRA_11', '' AS 'EXTRA_12', 
    '' AS 'EXTRA_13', '' AS 'EXTRA_14', '' AS 'EXTRA_15', '' AS 'EXTRA_16', '' AS 'EXTRA_17', '' AS 'EXTRA_18', 
    '' AS 'EXTRA_19', '' AS 'EXTRA_20' 

FROM
    vDocumentos

WHERE 
    ID_Cliente = 944
    AND NombreTipoDocumento = 'Albaran'
    AND RutaReparto = 'SCHENKER'
    AND CONVERT(date, FechaDoc) BETWEEN CONVERT(date, :inicio) AND CONVERT(date, :fin);

