apiVersion: v1
kind: Secret
metadata:
  name: msm-secret
  namespace: MSM
type: Opaque
stringData:
  SECRET_KEY: "cambiar por la real"
  DB_HOST: "postgres-cliente-a.internal"
  DB_NAME: "db-MSM"
  DB_USER: "MSM_user"
  DB_PASSWORD: "cambiar por la real"
  